name: Build and Deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3  # Update to v3
    
    - name: Install python
      uses: actions/setup-python@v4  # Update to v4
      with:
        python-version: '3.8'
    
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1'
    
    - name: Build Site
      run: |
        julia -e '
          using Pkg;
          Pkg.activate(".");
          Pkg.instantiate();
          using NodeJS;
          run(`$(npm_cmd()) install highlight.js`);
          using Franklin;
          optimize()'
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4  # Update to v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Updated syntax
        branch: gh-pages
        folder: __site

